name: sve_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - langchain==0.2.5
    - langchain-openai==0.1.8
    - python-dotenv==1.0.1
    - supabase==2.4.1
    - requests==2.32.3
    - beautifulsoup4==4.12.3
    - duckduckgo-search==6.1.8
